### ISSUE TITLE
scan qr

### ISSUE THREAD

**Issue by zstvn** [thoriqazzikraa/whatsapp-bot#104]
Abis scan qr kok gabisa aktif botnya ya? nomor kan ganti di #304 terus @c.us dibiarin kan?
*ps: pas dicoba untuk npm start ke dua kalinya, qr code ga muncul lagi

**Comment by thoriqazzikraa** [comment]
> Abis scan qr kok gabisa aktif botnya ya? nomor kan ganti di #304 terus @c.us dibiarin kan? *ps: pas dicoba untuk npm start ke dua kalinya, qr code ga muncul lagi

Coba ss pas abis scan qr
Dan klo udh scan qr pas pertama kali, buat yg keduanya ga perlu scan qr lagi

**Comment by zstvn** [comment]
bukan gitu, kita scannya pake nomer yang kita tulis di handlemsg bukan? 
abis gw scan, di hp gw muncul web whatsapp is active kan, tapi kaga bisa jawab command
pas gw coba dari awal lagi, scriptnya stuck dia authenticating

**Comment by zstvn** [comment]
![image](https://user-images.githubusercontent.com/100577753/170900495-0713470a-39c4-434a-b2a7-0b05f0b9a845.png)
![image](https://user-images.githubusercontent.com/100577753/170900516-9c7218f7-ce67-4079-adad-d516f0c86d1b.png)
eror gitu

**Comment by zstvn** [comment]
^^ pas discan tulisannya couldn't link device

**Comment by thoriqazzikraa** [comment]
> ![image](https://user-images.githubusercontent.com/100577753/170900516-9c7218f7-ce67-4079-adad-d516f0c86d1b.png) eror gitu

Oh ini emang suka kek gitu
Bug md keknya
Coba pake ini

`npm i --save @open-wa/wa-automate@latest`

trus sblm npm start hapus file URBAE.data.json, folder store sama _IGNORE_URBAE
Trus `npm start`

**Comment by zstvn** [comment]
jadi yang diganti ownernumber aja kan?

**Comment by thoriqazzikraa** [comment]
> jadi yang diganti ownernumber aja kan? jadi bingung ngetest chatnya ke nomer mana ![image](https://user-images.githubusercontent.com/100577753/170915248-7577a6a8-b4d3-483b-93d6-a7be615e3b26.png) abis nyoba cmmand random jadi ngecrash, terus mati botnya

Coba wa saya bang

https://wa.me/62895334951166

**Comment by zstvn** [comment]
udah bisa bang! mantep botnya
