### ISSUE TITLE
Throw errors while starting the script

### ISSUE THREAD

**Issue by Sunda001** [thoriqazzikraa/whatsapp-bot#109]
Node version: v12.22.12
Npm version: 6.14.16
![Screenshot_20220606-123751_Termux](https://user-images.githubusercontent.com/32301831/172101503-dbb85aa4-e51c-4fac-8d00-f3a910bb9a3c.png)

**Comment by thoriqazzikraa** [comment]
> Node version: v12.22.12 Npm version: 6.14.16 ![Screenshot_20220606-123751_Termux](https://user-images.githubusercontent.com/32301831/172101503-dbb85aa4-e51c-4fac-8d00-f3a910bb9a3c.png)

sorry, i'm gonna fixed it

**Comment by thoriqazzikraa** [comment]
> Node version: v12.22.12 Npm version: 6.14.16 ![Screenshot_20220606-123751_Termux](https://user-images.githubusercontent.com/32301831/172101503-dbb85aa4-e51c-4fac-8d00-f3a910bb9a3c.png)

[here's mate](https://github.com/thoriqazzikraa/whatsapp-bot/commit/0a938a2405392353ce49585d85f65f175d6bffc6)

**Comment by Sunda001** [comment]
Got another errors:
```
> whatsapp-bot@2.11.0 start /home/sakty/whatsapp-bot
> node index.js

/home/sakty/whatsapp-bot/node_modules/tiktok-scraper-ts/dist/main.js:1
var W=Object.create;var f=Object.defineProperty;var O=Object.getOwnPropertyDescriptor;var _=Object.getOwnPropertyNames;var q=Object.getPrototypeOf,D=Object.prototype.hasOwnProperty;var U=o=>f(o,"__esModule",{value:!0}),a=(o,r)=>f(o,"name",{value:r,configurable:!0});var j=(o,r)=>{for(var n in r)f(o,n,{get:r[n],enumerable:!0})},$=(o,r,n,s)=>{if(r&&typeof r=="object"||typeof r=="function")for(let e of _(r))!D.call(o,e)&&(n||e!=="default")&&f(o,e,{get:()=>r[e],enumerable:!(s=O(r,e))||s.enumerable});return o},v=(o,r)=>$(U(f(o!=null?W(q(o)):{},"default",!r&&o&&o.__esModule?{get:()=>o.default,enumerable:!0}:{value:o,enumerable:!0})),o),J=(o=>(r,n)=>o&&o.get(r)||(n=$(U({}),r,1),o&&o.set(r,n),n))(typeof WeakMap!="undefined"?new WeakMap:0);var z={};j(z,{Music:()=>p,TTScraper:()=>m,TikTokResult:()=>b,User:()=>I,Video:()=>g,fetchAllVideosFromUser:()=>P,fetchMusic:()=>F,fetchUser:()=>G,fetchVideo:()=>Y,fetchVideoNoWaterMark:()=>H,hashtag:()=>K});var

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/sakty/whatsapp-bot/HandleMsg.js:33:23)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/sakty/whatsapp-bot/index.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot@2.11.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot@2.11.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sakty/.npm/_logs/2022-06-06T17_18_22_756Z-debug.log
```

**Comment by thoriqazzikraa** [comment]
> Got another errors:
> 
> ```
> > whatsapp-bot@2.11.0 start /home/sakty/whatsapp-bot
> > node index.js
> 
> /home/sakty/whatsapp-bot/node_modules/tiktok-scraper-ts/dist/main.js:1
> var W=Object.create;var f=Object.defineProperty;var O=Object.getOwnPropertyDescriptor;var _=Object.getOwnPropertyNames;var q=Object.getPrototypeOf,D=Object.prototype.hasOwnProperty;var U=o=>f(o,"__esModule",{value:!0}),a=(o,r)=>f(o,"name",{value:r,configurable:!0});var j=(o,r)=>{for(var n in r)f(o,n,{get:r[n],enumerable:!0})},$=(o,r,n,s)=>{if(r&&typeof r=="object"||typeof r=="function")for(let e of _(r))!D.call(o,e)&&(n||e!=="default")&&f(o,e,{get:()=>r[e],enumerable:!(s=O(r,e))||s.enumerable});return o},v=(o,r)=>$(U(f(o!=null?W(q(o)):{},"default",!r&&o&&o.__esModule?{get:()=>o.default,enumerable:!0}:{value:o,enumerable:!0})),o),J=(o=>(r,n)=>o&&o.get(r)||(n=$(U({}),r,1),o&&o.set(r,n),n))(typeof WeakMap!="undefined"?new WeakMap:0);var z={};j(z,{Music:()=>p,TTScraper:()=>m,TikTokResult:()=>b,User:()=>I,Video:()=>g,fetchAllVideosFromUser:()=>P,fetchMusic:()=>F,fetchUser:()=>G,fetchVideo:()=>Y,fetchVideoNoWaterMark:()=>H,hashtag:()=>K});var
> 
> SyntaxError: Unexpected token .
>     at Module._compile (internal/modules/cjs/loader.js:703:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>     at Module.load (internal/modules/cjs/loader.js:628:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>     at Module.require (internal/modules/cjs/loader.js:666:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Object.<anonymous> (/home/sakty/whatsapp-bot/HandleMsg.js:33:23)
>     at Module._compile (internal/modules/cjs/loader.js:759:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>     at Module.load (internal/modules/cjs/loader.js:628:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>     at Module.require (internal/modules/cjs/loader.js:666:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Object.<anonymous> (/home/sakty/whatsapp-bot/index.js:8:19)
>     at Module._compile (internal/modules/cjs/loader.js:759:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>     at Module.load (internal/modules/cjs/loader.js:628:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
>     at internal/main/run_main_module.js:17:11
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! whatsapp-bot@2.11.0 start: `node index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the whatsapp-bot@2.11.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/sakty/.npm/_logs/2022-06-06T17_18_22_756Z-debug.log
> ```

try with nodejs version 14 LTS FERMIUM

**Comment by thoriqazzikraa** [comment]
look you have nodejs with 12 version

**Comment by Sunda001** [comment]
> > Got another errors:
> > ```
> > > whatsapp-bot@2.11.0 start /home/sakty/whatsapp-bot
> > > node index.js
> > 
> > /home/sakty/whatsapp-bot/node_modules/tiktok-scraper-ts/dist/main.js:1
> > var W=Object.create;var f=Object.defineProperty;var O=Object.getOwnPropertyDescriptor;var _=Object.getOwnPropertyNames;var q=Object.getPrototypeOf,D=Object.prototype.hasOwnProperty;var U=o=>f(o,"__esModule",{value:!0}),a=(o,r)=>f(o,"name",{value:r,configurable:!0});var j=(o,r)=>{for(var n in r)f(o,n,{get:r[n],enumerable:!0})},$=(o,r,n,s)=>{if(r&&typeof r=="object"||typeof r=="function")for(let e of _(r))!D.call(o,e)&&(n||e!=="default")&&f(o,e,{get:()=>r[e],enumerable:!(s=O(r,e))||s.enumerable});return o},v=(o,r)=>$(U(f(o!=null?W(q(o)):{},"default",!r&&o&&o.__esModule?{get:()=>o.default,enumerable:!0}:{value:o,enumerable:!0})),o),J=(o=>(r,n)=>o&&o.get(r)||(n=$(U({}),r,1),o&&o.set(r,n),n))(typeof WeakMap!="undefined"?new WeakMap:0);var z={};j(z,{Music:()=>p,TTScraper:()=>m,TikTokResult:()=>b,User:()=>I,Video:()=>g,fetchAllVideosFromUser:()=>P,fetchMusic:()=>F,fetchUser:()=>G,fetchVideo:()=>Y,fetchVideoNoWaterMark:()=>H,hashtag:()=>K});var
> > 
> > SyntaxError: Unexpected token .
> >     at Module._compile (internal/modules/cjs/loader.js:703:23)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
> >     at Module.load (internal/modules/cjs/loader.js:628:32)
> >     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
> >     at Module.require (internal/modules/cjs/loader.js:666:19)
> >     at require (internal/modules/cjs/helpers.js:16:16)
> >     at Object.<anonymous> (/home/sakty/whatsapp-bot/HandleMsg.js:33:23)
> >     at Module._compile (internal/modules/cjs/loader.js:759:30)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
> >     at Module.load (internal/modules/cjs/loader.js:628:32)
> >     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
> >     at Module.require (internal/modules/cjs/loader.js:666:19)
> >     at require (internal/modules/cjs/helpers.js:16:16)
> >     at Object.<anonymous> (/home/sakty/whatsapp-bot/index.js:8:19)
> >     at Module._compile (internal/modules/cjs/loader.js:759:30)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
> >     at Module.load (internal/modules/cjs/loader.js:628:32)
> >     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
> >     at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
> >     at internal/main/run_main_module.js:17:11
> > npm ERR! code ELIFECYCLE
> > npm ERR! errno 1
> > npm ERR! whatsapp-bot@2.11.0 start: `node index.js`
> > npm ERR! Exit status 1
> > npm ERR!
> > npm ERR! Failed at the whatsapp-bot@2.11.0 start script.
> > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > 
> > npm ERR! A complete log of this run can be found in:
> > npm ERR!     /home/sakty/.npm/_logs/2022-06-06T17_18_22_756Z-debug.log
> > ```
> 
> try with nodejs version 14 LTS FERMIUM

Wait lemme change

**Comment by Sunda001** [comment]
Got this errors
```
> whatsapp-bot@2.11.0 start /home/sakty/whatsapp-bot
> node index.js                                               
internal/modules/cjs/loader.js:1102                                 throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);                                                           ^
                                                              Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/sakty/whatsapp-bot/node_modules/node-fetch/src/index.js   require() of ES modules is not supported.
require() of /home/sakty/whatsapp-bot/node_modules/node-fetch/src/index.js from /home/sakty/whatsapp-bot/HandleMsg.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.                           Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/sakty/whatsapp-bot/node_modules/node-fetch/package.json.
                                                                  at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)     at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/sakty/whatsapp-bot/HandleMsg.js:32:15)                                                         at Module._compile (internal/modules/cjs/loader.js:1085:14)                                                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)                                                            at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)           at Object.<anonymous> (/home/sakty/whatsapp-bot/index.js:8:19)                                                              at Module._compile (internal/modules/cjs/loader.js:1085:14)                                                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {                 code: 'ERR_REQUIRE_ESM'
}                                                             npm ERR! code ELIFECYCLE
npm ERR! errno 1                                              npm ERR! whatsapp-bot@2.11.0 start: `node index.js`
npm ERR! Exit status 1                                        npm ERR!
npm ERR! Failed at the whatsapp-bot@2.11.0 start script.      npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I have removed  "type": "module" but showing another errors:
 ```
> whatsapp-bot@2.11.0 start /home/sakty/whatsapp-bot          > node index.js                                                                                                             /home/sakty/whatsapp-bot/node_modules/node-fetch/src/index.js:9                                                             import http from 'node:http';                                 ^^^^^^
                                                              SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)          at Module._compile (internal/modules/cjs/loader.js:1049:27)                                                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)     at require (internal/modules/cjs/helpers.js:101:18)           at Object.<anonymous> (/home/sakty/whatsapp-bot/HandleMsg.js:32:15)                                                         at Module._compile (internal/modules/cjs/loader.js:1085:14)                                                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)     at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/sakty/whatsapp-bot/index.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)        at Function.Module._load (internal/modules/cjs/loader.js:790:12)                                                            at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)                                         at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE                                      npm ERR! errno 1
npm ERR! whatsapp-bot@2.11.0 start: `node index.js`           npm ERR! Exit status 1
npm ERR!                                                      npm ERR! Failed at the whatsapp-bot@2.11.0 start script.
```

**Comment by thoriqazzikraa** [comment]
> Got this errors
> 
> ```
> > whatsapp-bot@2.11.0 start /home/sakty/whatsapp-bot
> > node index.js                                               
> internal/modules/cjs/loader.js:1102                                 throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);                                                           ^
>                                                               Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/sakty/whatsapp-bot/node_modules/node-fetch/src/index.js   require() of ES modules is not supported.
> require() of /home/sakty/whatsapp-bot/node_modules/node-fetch/src/index.js from /home/sakty/whatsapp-bot/HandleMsg.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.                           Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/sakty/whatsapp-bot/node_modules/node-fetch/package.json.
>                                                                   at new NodeError (internal/errors.js:322:7)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
>     at Module.require (internal/modules/cjs/loader.js:974:19)     at require (internal/modules/cjs/helpers.js:101:18)
>     at Object.<anonymous> (/home/sakty/whatsapp-bot/HandleMsg.js:32:15)                                                         at Module._compile (internal/modules/cjs/loader.js:1085:14)                                                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:12)                                                            at Module.require (internal/modules/cjs/loader.js:974:19)
>     at require (internal/modules/cjs/helpers.js:101:18)           at Object.<anonymous> (/home/sakty/whatsapp-bot/index.js:8:19)                                                              at Module._compile (internal/modules/cjs/loader.js:1085:14)                                                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
>     at internal/main/run_main_module.js:17:47 {                 code: 'ERR_REQUIRE_ESM'
> }                                                             npm ERR! code ELIFECYCLE
> npm ERR! errno 1                                              npm ERR! whatsapp-bot@2.11.0 start: `node index.js`
> npm ERR! Exit status 1                                        npm ERR!
> npm ERR! Failed at the whatsapp-bot@2.11.0 start script.      npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> ```
> 
> I have removed "type": "module" but showing another errors:
> 
> ```
> > whatsapp-bot@2.11.0 start /home/sakty/whatsapp-bot          > node index.js                                                                                                             /home/sakty/whatsapp-bot/node_modules/node-fetch/src/index.js:9                                                             import http from 'node:http';                                 ^^^^^^
>                                                              SyntaxError: Cannot use import statement outside a module
>    at wrapSafe (internal/modules/cjs/loader.js:1001:16)          at Module._compile (internal/modules/cjs/loader.js:1049:27)                                                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)
>    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
>    at Module.require (internal/modules/cjs/loader.js:974:19)     at require (internal/modules/cjs/helpers.js:101:18)           at Object.<anonymous> (/home/sakty/whatsapp-bot/HandleMsg.js:32:15)                                                         at Module._compile (internal/modules/cjs/loader.js:1085:14)                                                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)
>    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
>    at Module.require (internal/modules/cjs/loader.js:974:19)     at require (internal/modules/cjs/helpers.js:101:18)
>    at Object.<anonymous> (/home/sakty/whatsapp-bot/index.js:8:19)
>    at Module._compile (internal/modules/cjs/loader.js:1085:14)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>    at Module.load (internal/modules/cjs/loader.js:950:32)        at Function.Module._load (internal/modules/cjs/loader.js:790:12)                                                            at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)                                         at internal/main/run_main_module.js:17:47
> npm ERR! code ELIFECYCLE                                      npm ERR! errno 1
> npm ERR! whatsapp-bot@2.11.0 start: `node index.js`           npm ERR! Exit status 1
> npm ERR!                                                      npm ERR! Failed at the whatsapp-bot@2.11.0 start script.
> ```

what nodejs version you installed?

**Comment by Sunda001** [comment]
v14.19.3

**Comment by thoriqazzikraa** [comment]
> v14.19.3

use 14.17.3

**Comment by Sunda001** [comment]
Still same:
> whatsapp-bot@2.11.0 start /home/sakty/whatsapp-bot          > node index.js                                                                                                             internal/modules/cjs/loader.js:1102                                 throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);                                                           ^                                                                                                                     Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/sakty/whatsapp-bot/node_modules/node-fetch/src/index.js   require() of ES modules is not supported.
require() of /home/sakty/whatsapp-bot/node_modules/node-fetch/src/index.js from /home/sakty/whatsapp-bot/HandleMsg.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.                           Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/sakty/whatsapp-bot/node_modules/node-fetch/package.json.                                                                           at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)        at Function.Module._load (internal/modules/cjs/loader.js:790:14)                                                            at Module.require (internal/modules/cjs/loader.js:974:19)     at require (internal/modules/cjs/helpers.js:92:18)            at Object.<anonymous> (/home/sakty/whatsapp-bot/HandleMsg.js:32:15)                                                         at Module._compile (internal/modules/cjs/loader.js:1085:14)                                                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)        at Function.Module._load (internal/modules/cjs/loader.js:790:14)                                                            at Module.require (internal/modules/cjs/loader.js:974:19)     at require (internal/modules/cjs/helpers.js:92:18)            at Object.<anonymous> (/home/sakty/whatsapp-bot/index.js:8:19)                                                              at Module._compile (internal/modules/cjs/loader.js:1085:14)                                                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)        at Function.Module._load (internal/modules/cjs/loader.js:790:14)                                                            at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)                                         at internal/main/run_main_module.js:17:47 {
  code: 'ERR_REQUIRE_ESM'                                     }
npm ERR! code ELIFECYCLE                                      npm ERR! errno 1                                              npm ERR! whatsapp-bot@2.11.0 start: `node index.js`           npm ERR! Exit status 1                                        npm ERR!                                                      npm ERR! Failed at the whatsapp-bot@2.11.0 start script.

**Comment by thoriqazzikraa** [comment]
> Still same:
> 
> > whatsapp-bot@2.11.0 start /home/sakty/whatsapp-bot          > node index.js                                                                                                             internal/modules/cjs/loader.js:1102                                 throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);                                                           ^                                                                                                                     Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/sakty/whatsapp-bot/node_modules/node-fetch/src/index.js   require() of ES modules is not supported.
> > require() of /home/sakty/whatsapp-bot/node_modules/node-fetch/src/index.js from /home/sakty/whatsapp-bot/HandleMsg.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.                           Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/sakty/whatsapp-bot/node_modules/node-fetch/package.json.                                                                           at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)        at Function.Module._load (internal/modules/cjs/loader.js:790:14)                                                            at Module.require (internal/modules/cjs/loader.js:974:19)     at require (internal/modules/cjs/helpers.js:92:18)            at Object. (/home/sakty/whatsapp-bot/HandleMsg.js:32:15)                                                         at Module._compile (internal/modules/cjs/loader.js:1085:14)                                                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)        at Function.Module._load (internal/modules/cjs/loader.js:790:14)                                                            at Module.require (internal/modules/cjs/loader.js:974:19)     at require (internal/modules/cjs/helpers.js:92:18)            at Object. (/home/sakty/whatsapp-bot/index.js:8:19)                                                              at Module._compile (internal/modules/cjs/loader.js:1085:14)                                                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)                                                   at Module.load (internal/modules/cjs/loader.js:950:32)        at Function.Module._load (internal/modules/cjs/loader.js:790:14)                                                            at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)                                         at internal/main/run_main_module.js:17:47 {
> > code: 'ERR_REQUIRE_ESM'                                     }
> > npm ERR! code ELIFECYCLE                                      npm ERR! errno 1                                              npm ERR! whatsapp-bot@2.11.0 start: `node index.js`           npm ERR! Exit status 1                                        npm ERR!                                                      npm ERR! Failed at the whatsapp-bot@2.11.0 start script.

try again with 14.17.0

**Comment by thoriqazzikraa** [comment]
i see people comment it's fixed on that version

**Comment by Sunda001** [comment]
![Uploading Screenshot_20220607-012635_Termux.png…]()
Still same

**Comment by thoriqazzikraa** [comment]
> ![Screenshot_20220607-012635_Termux](https://user-images.githubusercontent.com/32301831/172222984-8273553b-dea9-4351-bd74-fdd7d46d8c58.png) Still same

can you screenshot above on console?
i can't see type of error

**Comment by thoriqazzikraa** [comment]
> ![Screenshot_20220607-012635_Termux](https://user-images.githubusercontent.com/32301831/172222984-8273553b-dea9-4351-bd74-fdd7d46d8c58.png) Still same

and don't use termux, my repo don't work with that app

**Comment by thoriqazzikraa** [comment]
> > ![Screenshot_20220607-012635_Termux](https://user-images.githubusercontent.com/32301831/172222984-8273553b-dea9-4351-bd74-fdd7d46d8c58.png) Still same
> 
> and don't use termux, my repo doesn't work with that app

**Comment by Sunda001** [comment]
> > ![Screenshot_20220607-012635_Termux](https://user-images.githubusercontent.com/32301831/172222984-8273553b-dea9-4351-bd74-fdd7d46d8c58.png) Still same
> 
> and don't use termux, my repo doesn't work with that app

Dude its vps, look at the cwd termux home isnt startswith '/home' its vps, i use termux to use the vps...

**Comment by Sunda001** [comment]
![Screenshot_20220607-130114_Termux](https://user-images.githubusercontent.com/32301831/172306887-ed978b47-0301-47de-aad2-25a157fa3e32.png)

**Comment by thoriqazzikraa** [comment]
> > > ![Screenshot_20220607-012635_Termux](https://user-images.githubusercontent.com/32301831/172222984-8273553b-dea9-4351-bd74-fdd7d46d8c58.png) Still same
> > 
> > 
> > and don't use termux, my repo doesn't work with that app
> 
> Dude its vps, look at the cwd, termux home isnt startswith '/home' so its vps, i use termux to use the vps...

oh sorry, it is still error?

**Comment by Sunda001** [comment]
> > > > ![Screenshot_20220607-012635_Termux](https://user-images.githubusercontent.com/32301831/172222984-8273553b-dea9-4351-bd74-fdd7d46d8c58.png) Still same
> > > 
> > > 
> > > and don't use termux, my repo doesn't work with that app
> > 
> > 
> > Dude its vps, look at the cwd, termux home isnt startswith '/home' so its vps, i use termux to use the vps...
> 
> oh sorry, it is still error?

Yeah

**Comment by thoriqazzikraa** [comment]
> > > ![Screenshot_20220607-012635_Termux](https://user-images.githubusercontent.com/32301831/172222984-8273553b-dea9-4351-bd74-fdd7d46d8c58.png) Still same
> > 
> > 
> > and don't use termux, my repo doesn't work with that app

please screenshot on above
i can't see type of error

**Comment by Sunda001** [comment]
![Screenshot_20220607-152644_Termux](https://user-images.githubusercontent.com/32301831/172334480-11d78c5f-2abb-4f38-9b2d-4804ad6a3a54.png)

**Comment by thoriqazzikraa** [comment]
> ![Screenshot_20220607-152644_Termux](https://user-images.githubusercontent.com/32301831/172334480-11d78c5f-2abb-4f38-9b2d-4804ad6a3a54.png)

[See this](https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module)
