### ISSUE TITLE
Gabisa pake fitur tiktok

### ISSUE THREAD

**Issue by raooyz** [thoriqazzikraa/whatsapp-bot#122]
![9421C885-7D13-4606-A1D3-3E7B7744A2D0](https://user-images.githubusercontent.com/76953279/179285624-444d0b01-b7f7-4b32-ab83-fd490c4e2a96.jpeg)
![048C52BC-4E27-4359-BDC3-5A425D10EA7A](https://user-images.githubusercontent.com/76953279/179285637-c55850f2-66a7-48c9-a61d-2e9f8fd5444d.jpeg)

Ini kenapa ya /tiktok selalu keluar gitu

**Comment by raooyz** [comment]
Di cmd nya gaada masalah, tapi hasilnya begitu

**Comment by Sansekai** [comment]
> Di cmd nya gaada masalah, tapi hasilnya begitu

Update versi open-wa nya

`npm i @open-wa/wa-automate@latest`

**Comment by raooyz** [comment]
PS C:\Users\lutfe\Downloads\bot\whatsapp-bot> npm i @open-wa/wa-automate@latest
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> unix-dgram@2.0.4 install C:\Users\lutfe\Downloads\Bot\whatsapp-bot\node_modules\unix-dgram
> node-gyp rebuild


C:\Users\lutfe\Downloads\Bot\whatsapp-bot\node_modules\unix-dgram>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:326:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:338:5)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:467:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lutfe\Downloads\Bot\whatsapp-bot\node_modules\unix-dgram
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> @open-wa/wa-automate@4.42.7 install C:\Users\lutfe\Downloads\Bot\whatsapp-bot\node_modules\@open-wa\wa-automate
> cross-env npm_config_yes=true npx ignore-check@latest -p '**.data.json' -p '**.node-persist**' -p '**_IGNORE_**' --comment 'managed by open-wa'

npx: installed 61 in 30.43s

***.GITIGNORE CHECK***

Patterns (**.data.json, **.node-persist**, **_IGNORE_**) already present in .gitignore (C:\Users\lutfe\Downloads\Bot\whatsapp-bot\.gitignore)

***


> @open-wa/wa-automate@4.42.7 postinstall C:\Users\lutfe\Downloads\Bot\whatsapp-bot\node_modules\@open-wa\wa-automate
> patch-package

patch-package 6.4.7
Applying patches...
No patch files found
npm WARN notsup Unsupported engine for @open-wa/wa-automate@4.42.7: wanted: {"node":">=12.18.3","npm":">=7.9.0"} (current: {"node":"14.17.0","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: @open-wa/wa-automate@4.42.7
npm WARN notsup Unsupported engine for @discordjs/collection@0.5.0: wanted: {"node":">=16.9.0"} (current: {"node":"14.17.0","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: @discordjs/collection@0.5.0
npm WARN notsup Unsupported engine for @open-wa/wa-automate-types-only@4.42.7: wanted: {"node":">=12.18.3","npm":">=7.9.0"} (current: {"node":"14.17.0","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: @open-wa/wa-automate-types-only@4.42.7
npm WARN flag@4.4.0 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN flag@4.4.0 requires a peer of @types/react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN flag@4.4.0 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN flag@4.4.0 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN flag@4.4.0 requires a peer of react-redux@^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN flag@4.4.0 requires a peer of redux@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN swagger-stats@0.99.2 requires a peer of prom-client@>= 10 <= 13 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-android-arm64@0.1.25 (node_modules\@napi-rs\canvas-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-android-arm64@0.1.25: wanted {"os":"android","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-darwin-arm64@0.1.25 (node_modules\@napi-rs\canvas-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-darwin-arm64@0.1.25: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-darwin-x64@0.1.25 (node_modules\@napi-rs\canvas-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-darwin-x64@0.1.25: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-arm-gnueabihf@0.1.25 (node_modules\@napi-rs\canvas-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-arm-gnueabihf@0.1.25: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-arm64-gnu@0.1.25 (node_modules\@napi-rs\canvas-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-arm64-gnu@0.1.25: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-arm64-musl@0.1.25 (node_modules\@napi-rs\canvas-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-arm64-musl@0.1.25: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-x64-gnu@0.1.25 (node_modules\@napi-rs\canvas-linux-x64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-x64-gnu@0.1.25: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-x64-musl@0.1.25 (node_modules\@napi-rs\canvas-linux-x64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-x64-musl@0.1.25: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@2.0.4 (node_modules\unix-dgram):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@2.0.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @open-wa/wa-automate@4.42.7
updated 2 packages and audited 1386 packages in 221.582s

94 packages are looking for funding
  run `npm fund` for details

found 19 vulnerabilities (9 moderate, 9 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by raooyz** [comment]
[EXEC] 16/07/22 17:30:33 /tiktok [1] from xiu
Error: Evaluation failed: Error: InvalidMediaFileType
    at y.sendToChat (https://web.whatsapp.com/bootstrap_qr.2c01e0e4abde696b6ff5.js:75:320907)
    at pptr://__puppeteer_evaluation_script__:1:189567
    at async window.<computed>.<computed> [as sendImage] (pptr://__puppeteer_evaluation_script__:1:186148)
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\lutfe\Downloads\Bot\whatsapp-bot\node_modules\puppeteer\src\common\ExecutionContext.ts:306:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ExecutionContext.evaluate (C:\Users\lutfe\Downloads\Bot\whatsapp-bot\node_modules\puppeteer\src\common\ExecutionContext.ts:150:12)

**Comment by thoriqazzikraa** [comment]
> [EXEC] 16/07/22 17:30:33 /tiktok [1] from xiu Error: Evaluation failed: Error: InvalidMediaFileType at y.sendToChat (https://web.whatsapp.com/bootstrap_qr.2c01e0e4abde696b6ff5.js:75:320907) at pptr://**puppeteer_evaluation_script**:1:189567 at async window.. [as sendImage] (pptr://**puppeteer_evaluation_script**:1:186148) at ExecutionContext._ExecutionContext_evaluate (C:\Users\lutfe\Downloads\Bot\whatsapp-bot\node_modules\puppeteer\src\common\ExecutionContext.ts:306:13) at processTicksAndRejections (internal/process/task_queues.js:95:5) at ExecutionContext.evaluate (C:\Users\lutfe\Downloads\Bot\whatsapp-bot\node_modules\puppeteer\src\common\ExecutionContext.ts:150:12)

gw tiktok make module atau scrape? lupa gw😅

**Comment by thoriqazzikraa** [comment]
> ![9421C885-7D13-4606-A1D3-3E7B7744A2D0](https://user-images.githubusercontent.com/76953279/179285624-444d0b01-b7f7-4b32-ab83-fd490c4e2a96.jpeg) ![048C52BC-4E27-4359-BDC3-5A425D10EA7A](https://user-images.githubusercontent.com/76953279/179285637-c55850f2-66a7-48c9-a61d-2e9f8fd5444d.jpeg)
> 
> Ini kenapa ya /tiktok selalu keluar gitu

solved on new update✅
