### ISSUE TITLE
Abis npm install langsung error

### ISSUE THREAD

**Issue by akraabiyu** [thoriqazzikraa/whatsapp-bot#124]
HP-Laptop-14s-dk0xxx:~/Downloads/bots$ npm install

> xfarr-api@2.0.0 preinstall /home/lutfey/Downloads/bots/node_modules/xfarr-api
> npm install -g deobfuscator

/home/lutfey/.nvm/versions/node/v14.17.3/bin/synchrony -> /home/lutfey/.nvm/versions/node/v14.17.3/lib/node_modules/deobfuscator/dist/cli.js
+ deobfuscator@2.3.0
updated 1 package in 3.652s

> @napi-rs/canvas-linux-x64-gnu@0.1.25 install /home/lutfey/Downloads/bots/node_modules/@napi-rs/canvas-linux-x64-gnu
> node install.js

> @napi-rs/canvas-linux-x64-musl@0.1.25 install /home/lutfey/Downloads/bots/node_modules/@napi-rs/canvas-linux-x64-musl
> node install.js

> unix-dgram@2.0.4 install /home/lutfey/Downloads/bots/node_modules/unix-dgram
> node-gyp rebuild

make: Entering directory '/home/lutfey/Downloads/bots/node_modules/unix-dgram/build'
  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
In file included from ../../nan/nan.h:60,
                 from ../src/unix_dgram.cc:5:
/home/lutfey/.cache/node-gyp/14.17.3/include/node/node.h:758:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  758 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lutfey/.cache/node-gyp/14.17.3/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/unix_dgram.cc:404:1: note: in expansion of macro ‘NODE_MODULE’
  404 | NODE_MODULE(unix_dgram, Initialize)
      | ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/unix_dgram.node
  COPY Release/unix_dgram.node
make: Leaving directory '/home/lutfey/Downloads/bots/node_modules/unix-dgram/build'

> puppeteer@15.0.0 install /home/lutfey/Downloads/bots/node_modules/puppeteer
> node install.js

Downloading Chromium r1002410 - 149 Mb [====================] 100% 0.0s 
Chromium (1002410) downloaded to /home/lutfey/Downloads/bots/node_modules/puppeteer/.local-chromium/linux-1002410

> @open-wa/wa-automate@4.42.7 install /home/lutfey/Downloads/bots/node_modules/@open-wa/wa-automate
> cross-env npm_config_yes=true npx ignore-check@latest -p '**.data.json' -p '**.node-persist**' -p '**_IGNORE_**' --comment 'managed by open-wa'

npx: installed 61 in 11.982s

***.GITIGNORE CHECK***

Patterns (**.data.json, **.node-persist**, **_IGNORE_**) already present in .gitignore (/home/lutfey/Downloads/bots/.gitignore)

***

> sharp@0.28.3 install /home/lutfey/Downloads/bots/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using cached /home/lutfey/.npm/_libvips/libvips-8.10.6-linux-x64.tar.br

> es5-ext@0.10.61 postinstall /home/lutfey/Downloads/bots/node_modules/es5-ext
>  node -e "try{require('./_postinstall')}catch(e){}" || exit 0

> javascript-obfuscator@4.0.0 postinstall /home/lutfey/Downloads/bots/node_modules/javascript-obfuscator
> opencollective-postinstall

Thank you for using javascript-obfuscator!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/javascript-obfuscator/donate

> @open-wa/wa-automate@4.42.7 postinstall /home/lutfey/Downloads/bots/node_modules/@open-wa/wa-automate
> patch-package

patch-package 6.4.7
Applying patches...
No patch files found

> canvacord@5.4.1 postinstall /home/lutfey/Downloads/bots/node_modules/canvacord
> node scripts/postinstall.mjs

[Canvacord] Downloading assets...
[Canvacord] Successfully downloaded metadata!
[Canvacord] Downloading images...
[Canvacord] Successfully downloaded CAPTCHA.png
[Canvacord] Successfully downloaded DELETE.png
[Canvacord] Successfully downloaded DISCORD.png
[Canvacord] Successfully downloaded IMPOSTER.png
[Canvacord] Successfully downloaded IMPOSTERWITH.png
[Canvacord] Successfully downloaded JAIL.png
[Canvacord] Successfully downloaded IDLE.png
[Canvacord] Successfully downloaded JOKEOVERHEAD.png
[Canvacord] Successfully downloaded ONLINE.png
[Canvacord] Successfully downloaded PHUB.png
[Canvacord] Successfully downloaded BOTBADGE.png
[Canvacord] Successfully downloaded WASTED.png
[Canvacord] Successfully downloaded GAY.png
[Canvacord] Successfully downloaded DND.png
[Canvacord] Successfully downloaded CLYDE.png
[Canvacord] Successfully downloaded YOUTUBE.png
[Canvacord] Successfully downloaded BEAUTIFUL.png
[Canvacord] Successfully downloaded KO.png
[Canvacord] Successfully downloaded RIP.png
[Canvacord] Successfully downloaded WELCOMEBG.png
[Canvacord] Successfully downloaded OFFLINE.png
[Canvacord] Successfully downloaded SHIT.png
[Canvacord] Successfully downloaded BED.png
[Canvacord] Successfully downloaded FACEPALM.png
[Canvacord] Successfully downloaded OHNO.png
[Canvacord] Successfully downloaded AFFECT.png
[Canvacord] Successfully downloaded KICK.png
[Canvacord] Successfully downloaded PUNCH.png
[Canvacord] Successfully downloaded BATSLAP.png
[Canvacord] Successfully downloaded KISS.png
[Canvacord] Successfully downloaded DISTRACTED.png
[Canvacord] Successfully downloaded CHANGEMYMIND.png
[Canvacord] Successfully downloaded SNOWFLAKE.png
[Canvacord] Successfully downloaded WANTED.png
[Canvacord] Successfully downloaded SPANK.png

/home/lutfey/Downloads/bots/node_modules/canvacord/node_modules/node-fetch/lib/index.js:1491
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://raw.githubusercontent.com/CesiumLabs/canvacord/assets/data/images/CRAB.mp4 failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/home/lutfey/Downloads/bots/node_modules/canvacord/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (events.js:375:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:375:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-android-arm64@0.1.25 (node_modules/@napi-rs/canvas-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-android-arm64@0.1.25: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-darwin-arm64@0.1.25 (node_modules/@napi-rs/canvas-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-darwin-arm64@0.1.25: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-win32-x64-msvc@0.1.25 (node_modules/@napi-rs/canvas-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-win32-x64-msvc@0.1.25: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-darwin-x64@0.1.25 (node_modules/@napi-rs/canvas-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-darwin-x64@0.1.25: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-arm64-gnu@0.1.25 (node_modules/@napi-rs/canvas-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-arm64-gnu@0.1.25: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-arm-gnueabihf@0.1.25 (node_modules/@napi-rs/canvas-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-arm-gnueabihf@0.1.25: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-arm64-musl@0.1.25 (node_modules/@napi-rs/canvas-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-arm64-musl@0.1.25: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-x64-musl@0.1.25 (node_modules/@napi-rs/canvas-linux-x64-musl):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-x64-musl@0.1.25 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvacord@5.4.1 postinstall: `node scripts/postinstall.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvacord@5.4.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lutfey/.npm/_logs/2022-07-18T15_54_02_767Z-debug.log

logs : https://drive.google.com/file/d/1n1jff3W_hr49GJOiS40oVbUwKiASDKpv/view?usp=sharing

**Comment by thoriqazzikraa** [comment]
> HP-Laptop-14s-dk0xxx:~/Downloads/bots$ npm install
> 
> > xfarr-api@2.0.0 preinstall /home/lutfey/Downloads/bots/node_modules/xfarr-api
> > npm install -g deobfuscator
> 
> /home/lutfey/.nvm/versions/node/v14.17.3/bin/synchrony -> /home/lutfey/.nvm/versions/node/v14.17.3/lib/node_modules/deobfuscator/dist/cli.js
> 
> * deobfuscator@2.3.0
>   updated 1 package in 3.652s
> 
> > @napi-rs/canvas-linux-x64-gnu@0.1.25 install /home/lutfey/Downloads/bots/node_modules/@napi-rs/canvas-linux-x64-gnu
> > node install.js
> 
> > @napi-rs/canvas-linux-x64-musl@0.1.25 install /home/lutfey/Downloads/bots/node_modules/@napi-rs/canvas-linux-x64-musl
> > node install.js
> 
> > unix-dgram@2.0.4 install /home/lutfey/Downloads/bots/node_modules/unix-dgram
> > node-gyp rebuild
> 
> make: Entering directory '/home/lutfey/Downloads/bots/node_modules/unix-dgram/build' CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o In file included from ../../nan/nan.h:60, from ../src/unix_dgram.cc:5: /home/lutfey/.cache/node-gyp/14.17.3/include/node/node.h:758:7: warning: cast between incompatible function types from ‘void (_)(v8::Localv8::Object)’ to ‘node::addon_register_func’ {aka ‘void (_)(v8::Localv8::Object, v8::Localv8::Value, void*)’} [-Wcast-function-type] 758 | (node::addon_register_func) (regfunc), | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ /home/lutfey/.cache/node-gyp/14.17.3/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’ 792 | NODE_MODULE_X(modname, regfunc, NULL, 0) // NOLINT (readability/null_usage) | ^~~~~~~~~~~~~ ../src/unix_dgram.cc:404:1: note: in expansion of macro ‘NODE_MODULE’ 404 | NODE_MODULE(unix_dgram, Initialize) | ^~~~~~~~~~~ SOLINK_MODULE(target) Release/obj.target/unix_dgram.node COPY Release/unix_dgram.node make: Leaving directory '/home/lutfey/Downloads/bots/node_modules/unix-dgram/build'
> 
> > puppeteer@15.0.0 install /home/lutfey/Downloads/bots/node_modules/puppeteer
> > node install.js
> 
> Downloading Chromium r1002410 - 149 Mb [====================] 100% 0.0s Chromium (1002410) downloaded to /home/lutfey/Downloads/bots/node_modules/puppeteer/.local-chromium/linux-1002410
> 
> > @open-wa/wa-automate@4.42.7 install /home/lutfey/Downloads/bots/node_modules/@open-wa/wa-automate
> > cross-env npm_config_yes=true npx ignore-check@latest -p '**.data.json' -p '**.node-persist**' -p '**_IGNORE_**' --comment 'managed by open-wa'
> 
> npx: installed 61 in 11.982s
> 
> _**.GITIGNORE CHECK**_
> 
> Patterns (**.data.json, **.node-persist**, **_IGNORE_**) already present in .gitignore (/home/lutfey/Downloads/bots/.gitignore)
> 
> > sharp@0.28.3 install /home/lutfey/Downloads/bots/node_modules/sharp
> > (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
> 
> sharp: Using cached /home/lutfey/.npm/_libvips/libvips-8.10.6-linux-x64.tar.br
> 
> > es5-ext@0.10.61 postinstall /home/lutfey/Downloads/bots/node_modules/es5-ext
> > node -e "try{require('./_postinstall')}catch(e){}" || exit 0
> 
> > javascript-obfuscator@4.0.0 postinstall /home/lutfey/Downloads/bots/node_modules/javascript-obfuscator
> > opencollective-postinstall
> 
> Thank you for using javascript-obfuscator! If you rely on this package, please consider supporting our open collective:
> 
> > https://opencollective.com/javascript-obfuscator/donate
> 
> > @open-wa/wa-automate@4.42.7 postinstall /home/lutfey/Downloads/bots/node_modules/@open-wa/wa-automate
> > patch-package
> 
> patch-package 6.4.7 Applying patches... No patch files found
> 
> > canvacord@5.4.1 postinstall /home/lutfey/Downloads/bots/node_modules/canvacord
> > node scripts/postinstall.mjs
> 
> [Canvacord] Downloading assets... [Canvacord] Successfully downloaded metadata! [Canvacord] Downloading images... [Canvacord] Successfully downloaded CAPTCHA.png [Canvacord] Successfully downloaded DELETE.png [Canvacord] Successfully downloaded DISCORD.png [Canvacord] Successfully downloaded IMPOSTER.png [Canvacord] Successfully downloaded IMPOSTERWITH.png [Canvacord] Successfully downloaded JAIL.png [Canvacord] Successfully downloaded IDLE.png [Canvacord] Successfully downloaded JOKEOVERHEAD.png [Canvacord] Successfully downloaded ONLINE.png [Canvacord] Successfully downloaded PHUB.png [Canvacord] Successfully downloaded BOTBADGE.png [Canvacord] Successfully downloaded WASTED.png [Canvacord] Successfully downloaded GAY.png [Canvacord] Successfully downloaded DND.png [Canvacord] Successfully downloaded CLYDE.png [Canvacord] Successfully downloaded YOUTUBE.png [Canvacord] Successfully downloaded BEAUTIFUL.png [Canvacord] Successfully downloaded KO.png [Canvacord] Successfully downloaded RIP.png [Canvacord] Successfully downloaded WELCOMEBG.png [Canvacord] Successfully downloaded OFFLINE.png [Canvacord] Successfully downloaded SHIT.png [Canvacord] Successfully downloaded BED.png [Canvacord] Successfully downloaded FACEPALM.png [Canvacord] Successfully downloaded OHNO.png [Canvacord] Successfully downloaded AFFECT.png [Canvacord] Successfully downloaded KICK.png [Canvacord] Successfully downloaded PUNCH.png [Canvacord] Successfully downloaded BATSLAP.png [Canvacord] Successfully downloaded KISS.png [Canvacord] Successfully downloaded DISTRACTED.png [Canvacord] Successfully downloaded CHANGEMYMIND.png [Canvacord] Successfully downloaded SNOWFLAKE.png [Canvacord] Successfully downloaded WANTED.png [Canvacord] Successfully downloaded SPANK.png
> 
> /home/lutfey/Downloads/bots/node_modules/canvacord/node_modules/node-fetch/lib/index.js:1491 reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err)); ^ FetchError: request to https://raw.githubusercontent.com/CesiumLabs/canvacord/assets/data/images/CRAB.mp4 failed, reason: read ECONNRESET at ClientRequest. (/home/lutfey/Downloads/bots/node_modules/canvacord/node_modules/node-fetch/lib/index.js:1491:11) at ClientRequest.emit (events.js:375:28) at TLSSocket.socketErrorListener (_http_client.js:475:9) at TLSSocket.emit (events.js:375:28) at emitErrorNT (internal/streams/destroy.js:106:8) at emitErrorCloseNT (internal/streams/destroy.js:74:3) at processTicksAndRejections (internal/process/task_queues.js:82:21) { type: 'system', errno: 'ECONNRESET', code: 'ECONNRESET' } npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-android-arm64@0.1.25 (node_modules/@napi-rs/canvas-android-arm64): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-android-arm64@0.1.25: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-darwin-arm64@0.1.25 (node_modules/@napi-rs/canvas-darwin-arm64): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-darwin-arm64@0.1.25: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-win32-x64-msvc@0.1.25 (node_modules/@napi-rs/canvas-win32-x64-msvc): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-win32-x64-msvc@0.1.25: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-darwin-x64@0.1.25 (node_modules/@napi-rs/canvas-darwin-x64): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-darwin-x64@0.1.25: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-arm64-gnu@0.1.25 (node_modules/@napi-rs/canvas-linux-arm64-gnu): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-arm64-gnu@0.1.25: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-arm-gnueabihf@0.1.25 (node_modules/@napi-rs/canvas-linux-arm-gnueabihf): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-arm-gnueabihf@0.1.25: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-arm64-musl@0.1.25 (node_modules/@napi-rs/canvas-linux-arm64-musl): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-arm64-musl@0.1.25: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-x64-musl@0.1.25 (node_modules/@napi-rs/canvas-linux-x64-musl): npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-x64-musl@0.1.25 install: `node install.js` npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 
> npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! canvacord@5.4.1 postinstall: `node scripts/postinstall.mjs` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the canvacord@5.4.1 postinstall script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /home/lutfey/.npm/_logs/2022-07-18T15_54_02_767Z-debug.log
> 
> logs : https://drive.google.com/file/d/1n1jff3W_hr49GJOiS40oVbUwKiASDKpv/view?usp=sharing

coba ini

``` npm i canvacord@5.1.0 ```
