### ISSUE TITLE
kok gini bang?

### ISSUE THREAD

**Issue by fuadxtps23** [thoriqazzikraa/whatsapp-bot#149]
![image](https://user-images.githubusercontent.com/93533757/203732088-745ca3e0-573a-4cd5-a652-0eb8c60c0f77.png)

pas masukin command kek gitu

**Comment by fuadxtps23** [comment]
kapan di bales

**Comment by fuadxtps23** [comment]
eh gw berubah pikiran untuk download langsung dan gak ngeclone akhirnya bisa tapi balesannya gak muncul

**Comment by Slavecode** [comment]
> kapan di bales

Update versi open wa nya

`npm i @open-wa/wa-automate@latest`

**Comment by thoriqazzikraa** [comment]
> > kapan di bales
> 
> Update versi open wa nya
> 
> `npm i @open-wa/wa-automate@latest`

salah:v
makin di-update makin gaiso
stuck in aja versi owanya di 4.48.0
```npm i @open-wa/wa-automate@4.48.0```

itu yg update owa baru sendFilenya udah harus diubah akwowko

**Comment by thoriqazzikraa** [comment]
> ![image](https://user-images.githubusercontent.com/93533757/203732088-745ca3e0-573a-4cd5-a652-0eb8c60c0f77.png)
> 
> pas masukin command kek gitu

done ya

**Comment by Sansekai** [comment]
> > > kapan di bales
> > 
> > 
> > Update versi open wa nya
> > `npm i @open-wa/wa-automate@latest`
> 
> salah:v makin di-update makin gaiso stuck in aja versi owanya di 4.48.0 `npm i @open-wa/wa-automate@4.48.0`
> 
> itu yg update owa baru sendFilenya udah harus diubah akwowko

iya itu update terbaru harus pakai format filenya, kalau kosong pasti error.

**Comment by fuadxtps23** [comment]
> > ![image](https://user-images.githubusercontent.com/93533757/203732088-745ca3e0-573a-4cd5-a652-0eb8c60c0f77.png)
> > pas masukin command kek gitu
> 
> done ya

work bang ty
